// ERROR ACTIONS

export const POST_NEW_ERROR = 'error/POST_NEW_ERROR'
export const CLEAR_ERRORS_SUCCESS = 'error/CLEAR_ERRORS_SUCCESS'

// AUTH ACTIONS
export const SET_LOGGED_USER = 'auth/SET_LOGGED_USER';
export const SET_LOGGED_USER_FAILURE = 'auth/SET_LOGGED_USER_FAILURE';
export const SET_LOGOUT_USER = 'auth/SET_LOGOUT_USER';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';


// CATEGORY ACTIONS
export const FETCH_CATEGORIES_SUCCESS = "categories/FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_FAILURE = "categories/FETCH_CATEGORIES_FAILURE"

// DONATIONS ACTIONS
export const FETCH_MY_DONATIONS_SUCCESS = "donations/FETCH_MY_DONATIONS_SUCCESS"
export const POST_DONATION_SUCCESS = "donations/POST_DONATION_SUCCESS"
export const POST_DONATION_FAILURE = "donations/POST_DONATION_FAILURE"

// NOTIFICATION ACTIONS
export const FETCH_NOTIFICATION_SUCCESS = "notification/FETCH_NOTIFICATION_SUCCESS"
export const FETCH_NOTIFICATION_FAILURE = "notification/FETCH_NOTIFICATION_FAILURE"
