// AUTH ACTIONS
export const SET_LOGGED_USER = 'auth/SET_LOGGED_USER'; 
export const SET_LOGGED_USER_FAILURE = 'auth/SET_LOGGED_USER_FAILURE'; 
export const SET_LOGOUT_USER = 'auth/SET_LOGOUT_USER'; 
